#!/usr/bin/env bash

filename=$(basename $1)

tempname=/dev/shm/$filename
cp $1 $tempname

# adjust the time. add 2561s
exiftool -AllDates+='0:0:2561' $tempname

# get current time
timestamp_search=$(identify -format "%[EXIF:DateTime]" $tempname | awk '{print $2}' | sed s/://g)

# find matching gps sentence
fgrep "GNGGA,$timestamp_search" gps-log
GPSLatitude=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f3)
GPSLatitudeRef=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f4)
GPSLongitude=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f5)
GPSLongitudeRef=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f6)
GPSAltitude=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f10)
GPSAltitudeRef=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f11)

# put GPS data into tag
cmd="exiftool  \
    -GPSLatitude=$GPSLatitude \
    -GPSLatitudeRef=$GPSLatitudeRef \
    -GPSLongitude=$GPSLongitude \
    -GPSLongitudeRef=$GPSLongitudeRef \
    -GPSAltitude=$GPSAltitude \
    $tempname"
$cmd

# now seek back in syslog and find sensor data...
most_recent_tx=$(fgrep "GNGGA,$timestamp_search" syslog -B 50 | fgrep "TX: " | tail -n 1 | cut -d\  -f7-)
sentence_id=$(echo $most_recent_tx | cut -d, -f2)
external_temperature=$(echo $most_recent_tx | cut -d, -f8)
pressure=$(echo $most_recent_tx | cut -d, -f9)
humidity=$(echo $most_recent_tx | cut -d, -f10)
internal_temperature=$(echo $most_recent_tx | cut -d, -f11 | cut -d\* -f1) # FIXME wrapping

# format string to pass to identify
format="
Altitude=$GPSAltitude
$GPSLatitude $GPSLatitudeRef, $GPSLongitude $GPSLongitudeRef
TX id: $sentence_id
External: $external_temperature°C, ${pressure}mB, $humidity%%RH
Internal: $internal_temperature°C
%[EXIF:DateTime]
Exposure Time=%[exif:ExposureTime]
ISO=%[exif:ISOSpeedRatings]
Aperture F=%[exif:FNumber]"

# do the work
# note the identify subprocess inline...

convert $tempname -pointsize 100 -fill white -gravity southeast -annotate +0+0 "`identify -format \"$format\" $tempname`"  output/$filename

rm $tempname
