#!/usr/bin/env bash

set -e
set -u

threads=6
if [ "$1" != "" ]; then
    threads=$1
fi
echo "Running with $threads threads."

cd `dirname $(realpath $0)`

rm -rf output-combined
mkdir output-combined

find ../106___12/*JPG | sort | xargs -P $threads -n 1 ./combine-one
