#!/usr/bin/env bash

set -e

threads=6
if [ "$1" != "" ]; then
    threads=$1
fi
set -u
echo "Running with $threads threads."

cd `dirname $(realpath $0)`

rm -rf output-combined
mkdir output-combined

find ../EAGLE/home/pi/photos/2/*.jpg | sort | xargs -P $threads -n 1 ./combine-one
