#!/usr/bin/env bash

# takes a Canon image as reference time, and then
# looks up the rpi image from the logs

filename=$(basename $1)

tempname=/dev/shm/$filename
cp $1 $tempname

# imagemagick uses /tmp as default TMPDIR, so tell it to use something else:
export TMPDIR=/dev/shm/

# adjust the time. add 5093976s
exiftool -AllDates+='0:0:5093976' $tempname

# get current time
timestamp_search_colons=$(identify -format "%[EXIF:DateTime]" $tempname | awk '{print $2}')
timestamp_search=$(echo $timestamp_search_colons | sed s/://g)

# find matching gps sentence
fgrep "GNGGA,$timestamp_search" gps-log
GPSLatitude=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f3)
GPSLatitudeRef=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f4)
GPSLongitude=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f5)
GPSLongitudeRef=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f6)
GPSAltitude=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f10)
GPSAltitudeRef=$(fgrep "GNGGA,$timestamp_search" gps-log | cut -d, -f11)

# put GPS data into tag
cmd="exiftool  \
    -GPSLatitude=$GPSLatitude \
    -GPSLatitudeRef=$GPSLatitudeRef \
    -GPSLongitude=$GPSLongitude \
    -GPSLongitudeRef=$GPSLongitudeRef \
    -GPSAltitude=$GPSAltitude \
    $tempname"
$cmd

# force orientation to horizontal; some frames are sideways but this messes up output consistency
exiftool -Orientation#=1 $tempname

tracker_output_string=""
# now seek back in syslog and find sensor data...
most_recent_tx=$(fgrep "GNGGA,$timestamp_search" syslog -B 50 | fgrep "TX: \$\$SAM" | fgrep -v NOFIX | tail -n 1 | cut -d\  -f7-)
if [ "$most_recent_tx" != "" ]; then
    sentence_id=$(echo $most_recent_tx | cut -d, -f2)
    external_temperature=$(echo $most_recent_tx | cut -d, -f8)
    pressure=$(echo $most_recent_tx | cut -d, -f9)
    humidity=$(echo $most_recent_tx | cut -d, -f10)
    internal_temperature=$(echo $most_recent_tx | cut -d, -f11 | cut -d\* -f1) # FIXME wrapping
    if [ "$internal_temperature" != "" ]; then
        if [ ${internal_temperature%%.*} -gt 128 ]; then
            new_internal_temperature=$(echo $internal_temperature-256 | bc)
            echo "Internal temp ($internal_temperature) over 128, recalc=$new_internal_temperature"
            internal_temperature=$nnew_internal_temperatureew_internal_temperature
        fi
    fi
    tracker_output_string="SAM (sdcard)
Altitude=$GPSAltitude
$GPSLatitude $GPSLatitudeRef, $GPSLongitude $GPSLongitudeRef
TX id: $sentence_id
External: $external_temperature°C, ${pressure}mb, $humidity%%RH
Internal: $internal_temperature°C
"

else
    # if there is no matching telemetry string on-board, look it up from BUZZ:
    buzz_sentence_id=$(cat habitat-telemetry/HAB1-BUZZ-telemetry.json  | jq ".[] | select(.time <= \"$timestamp_search_colons\") | .sentence_id"  | tail -n 1)
    echo "BUZZ sentence_id: $buzz_sentence_id"
    latitude=$(cat habitat-telemetry/HAB1-BUZZ-telemetry.json | jq '.[] | select(.sentence_id == 2100) | .latitude')
    longitude=$(cat habitat-telemetry/HAB1-BUZZ-telemetry.json | jq '.[] | select(.sentence_id == 2100) | .latitude')
    altitude=$(cat habitat-telemetry/HAB1-BUZZ-telemetry.json | jq '.[] | select(.sentence_id == 2100) | .altitude')
    tracker_output_string="BUZZ
Altitude=$altitude
$latitude, $longitude
TX id: $buzz_sentence_id
"
fi

# and then seek back in syslog to find relevant rpi photo
most_recent_rpi_photo_id=$(fgrep "GNGGA,$timestamp_search" syslog -B 50 | fgrep "Camera: taking picture" | tail -n 1 | cut -d/ -f6)
most_recent_rpi_photo="../SAM-tracker-sdcard/photos/3/$most_recent_rpi_photo_id"
if [ "$most_recent_rpi_photo_id" == "" ]; then
    most_recent_rpi_photo="blank-rpi-frame.jpg"
fi
if [ ! -s "$most_recent_rpi_photo" ]; then
    most_recent_rpi_photo="blank-rpi-frame.jpg"
fi
echo "Pi photo: $most_recent_rpi_photo"

# format string to pass to identify
format="
Canon camera:  
Exposure Time=%[exif:ExposureTime]
ISO=%[exif:ISOSpeedRatings]
Aperture F=%[exif:FNumber]

Tracker: $tracker_output_string
%[EXIF:DateTime]
"

# do the work
# note the identify subprocess inline...

convert $tempname \
    -gravity northeast \
    $most_recent_rpi_photo +smush 0x0 \
    -gravity southeast \
    -pointsize 100 -fill black -stroke white \
    -annotate +0+0 "`identify -format \"$format\" \$tempname`" \
    output-combined/$filename

rm $tempname*
